apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lekko.fullname" . }}
  labels:
    {{- include "lekko.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lekko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lekko.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lekko.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- if .Values.lekko.gitSync.enabled }}
            - "--repo-path=/data/lekko"
          {{- else }}
            - "--repo-url={{ .Values.lekko.repoURL }}"
          {{- end}}
            - "--api-key=$(LEKKO_API_KEY)"
            - "--mode={{ .Values.lekko.gitSync.enabled | ternary "static" "default"}}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: LEKKO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lekko
                  key: api_key
          livenessProbe:
            failureThreshold: 3
            exec:
              command: ["bin/grpc-health-probe", "-addr=:{{ .Values.service.port }}"]
            initialDelaySeconds: 1
            periodSeconds: 20
          readinessProbe:
            failureThreshold: 3
            exec:
              command: ["bin/grpc-health-probe", "-addr=:{{ .Values.service.port }}"]
            initialDelaySeconds: 1
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.lekko.gitSync.enabled }}
          volumeMounts:
            - name: lekko-config
              mountPath: /data
        - name: lekko-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.6.2
          args:
            - --repo=git@github.com:{{ .Values.lekko.repoURL }}
            - --branch=main
            - --depth=1
            - --root=/data/lekko
            - --ssh=true
            - --dest=contents
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: ssh-key-secret
            mountPath: /etc/git-secret
            readOnly: true
          - name: lekko-config
            mountPath: /data
          {{- end }}
      initContainers:
      {{- if .Values.lekko.gitSync.enabled }}
      - name: lekko-boostrap
        image: k8s.gcr.io/git-sync/git-sync:v3.6.2
        args:
          - --repo=git@github.com:{{ .Values.lekko.repoURL }}
          - --branch=main
          - --depth=1
          - --root=/data/lekko
          - --ssh=true
          - --one-time
          - --dest=contents
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: ssh-key-secret
          mountPath: /etc/git-secret
          readOnly: true
        - name: lekko-config
          mountPath: /data
      volumes:
        - name: ssh-key-secret
          secret:
            secretName: ssh-key-secret
            defaultMode: 0400
        - name: lekko-config
          emptyDir:
            sizeLimit: 500Mi
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
